### ISSUE TITLE
PHP Warning: Undefined array key with PHP 8.0-8.2

### ISSUE THREAD

**Issue by uv21** [Zillion01/jpfaq#43] opened 2023-02-22 14:24 UTC
In TYPO3 11.5.24 i get the following error:

(1/1) #1476107295 TYPO3\CMS\Core\Error\Exception
PHP Warning: Undefined array key "excludeAlreadyDisplayedQuestions" in /var/www/public/typo3conf/ext/jpfaq/Classes/Controller/QuestionController.php line 84

I have tested Apache2 with PHP 8.0 / 8.1 and 8.2. Always the same error.

Same error also when installing the fix (https://github.com/Zillion01/jpfaq/pull/42) from tobikummer.

**Comment by Zillion01** [comment] 2023-02-22 15:08
I cannot reproduce this, however I think I know what causes it, I will bring out a fix.

**Comment by Zillion01** [comment] 2023-02-22 15:12
It occurs when there are no categories?

**Comment by Zillion01** [comment] 2023-02-26 13:14
11.6.1 has been released, possible this bug is fixed now

**Closed** 2023-02-28 10:56 UTC
